apiVersion: apps/v1
kind: Deployment
metadata:
    name: orion
    namespace: scheduled
    labels:
        app: orion
spec:
    replicas: 1
    selector:
        matchLabels:
            app: orion
    template:
        metadata:
            labels:
                app: orion
        spec:
            containers:
              - name: orion
                image: fiware/orion:latest
                imagePullPolicy: IfNotPresent
                ports:
                 - containerPort: 1026
                args: ["-dbhost", "mongoservice:27017", "-logLevel", "INFO"]