apiVersion: v1
kind: Service
metadata:
  name: sthcometproxy
  namespace: scheduled
spec:
  selector:
    app: sthcometproxy
  clusterIP: 10.48.0.14
  ports:
  - protocol: TCP
    port: 8667
    targetPort: 8667
